### ISSUE TITLE
Gonzales LESS parser failing on basic CSS (0.3.9)

### ISSUE THREAD

**Issue by cognivator** [SC5/sc5-styleguide#561]
The following source causes a Gonzales PE error,

_NOTE: Greatly simplified source trying to isolate the cause of the parse error_
```
// Colors
// 
// Our colors
//
// Styleguide 1.0
.color {
    color: #ffffff;
}
.background {
    background: #000000;
}
```

_... and the resulting Gonzales error,_
```
Could not parse used variables from section 1:
Parsing error: Please check the validity of the block starting from line #1

1*| }

Gonzales PE version: 3.0.0-16
Syntax: less
Express server listening on port 3001
Socket connection established (id: 78X9f3bf3uxJI7eaAAAA)
```

Modifying the source slightly by separating the two CSS selector blocks with a newline results in the following error,
```
Could not parse used variables from section 1:
Parsing error: Please check the validity of the block starting from line #3

1 |     background: #000000;
2 | }

Gonzales PE version: 3.0.0-16
Syntax: less
Express server listening on port 3001
Socket connection established (id: qLN5hPhdTX_ulJT8AAAA)
```

FWIW, the command line,
```
styleguide --kss-source "src/common/themes/theme-colors-base.less --style-source "src/common/themes/theme-colors-base.css --output "styleguide" --title "Styleguide Test" --server --port 3001
```
(_where style-source is the css generated from kss-source_)

Neither error is evident in v0.3.8.
It seems we have some continuing issues with Gonzales-PE...?

**Comment by hannu** [comment]
When style guide parses used variables from the KSS blocks it splits individual blocks. In some cases this could lead to incorrect CSS. This happens usually when CSS block is opened and closed in the different KSS blocks. For example:

```
.some-style {

// Header
//
// Our colors
//
// Styleguide 1.0

  color: red
}

// Header
//
// Something else
//
// Styleguide 1.1
```

After KSS blocks are splitted we try to parse used variables from the following CSS that is not valid anymore:
```
  color: red
} 
```

When this kind of error is detected style guide is unable to show related variables for that block but style guide should be generated properly otherwise and the section should be visible.
