### ISSUE TITLE
Elements with position: fixed

### ISSUE THREAD

**Issue by monochromer** [SC5/sc5-styleguide#926]
Hello!

Recently I started to learn **SC5 Style Guide Generator**. Thank you for your work!
There was such question. There is a component - a header with a fixed position (`position: fixed` in **css**).
Is there any way to change the styles to display a header not fixed in styleguide?

Thank you!

**Comment by varya** [comment]
Hi. I was thinking you'd ask in English. Are you comfortable if I answer in English here?

**Comment by monochromer** [comment]
Yes.

**Comment by varya** [comment]
When you build styles in `styleguide:applystyles`, you may provide additional CSS file which contain CSS  that overrides this property.

For example, all your css (let's say in SCSS syntax) sits in `scss` folder. And there is header.scss among them:

```
scss/
  header.scss
  footer.scss
  layout.scss
```

Ih `header.scss` you have your header styles:

```
.header {
// something
position: fixed;
// something
}
```

Then, for the styleguide you need to provide a file which would override this property. You may place it into `scss/_styleguide-fix.scss`. Inside write something like

```
.header {
position: initial !important;
}
```

This file should be provided for the `applystyles` gulp task:

```
gulp.task('styleguide:applystyles', function() {
  return gulp.src('scss/**/**.scss') // this would include all the files
    .pipe(sass({
      errLogToConsole: true
    }))
    .pipe(styleguide.applyStyles())
    .pipe(gulp.dest(outputPath));
});
```

However, when bundling styles for production, exclude this fixing file from it. Because it's only needed for the styleguide. Your task for building styles would look like this:

```
gulp.task('styles', function() {
  return gulp.src(['scss/**/**.scss', '!scss/_styleguide-fix.scss'])
    .pipe(sass({
      errLogToConsole: true
    }))
    .pipe(gulp.dest('my/build/path'));
})
```
