### ISSUE TITLE
Scripts included as part of extraHead are running twice

### ISSUE THREAD

**Issue by jaasum** [SC5/sc5-styleguide#953]
I'm not sure if this is a bug or just ignorance on my part.

I am passing an argument for `extraHead` as follows, with `--disableEncapsulation true`:

```
--extraHead "<script src=\"/js/styleguide.js\"></script>"
```

Within styleguide.js I have the following:

```
window.addEventListener('styleguide:onRendered', function() {
  var myFunction = function() {
    // Stuff to run on patterns here
  };
  myFunction();
});
```

When I'm debugging in the console I'm getting errors being thrown for click events basically saying things like "You cannot open your dialog, it's already open" and upon further debugging I am getting console messages printing twice. As far as I can tell, my script is getting included twice on the page, but inspecting the DOM doesn't seem to indicate two script tags being included. I'm at a loss as to how `myFunction();` could be triggered twice.

**Comment by varya** [comment]
This event emits every time a component is rendered or re-rendered.
The components are placed into the page with Angular which watches for the model changes and may re-draw the components when it thinks it's needed. So, the event may fire even 3 or 4 times, depending on the structure of the styleguide and usage.
I don't think that it should fire the event only once. Because the component may be re-rendered so that it needs JavaScript to re-run. This is why the event fires always.
But you know your code. And if it's for sure that you only need run this function one time, please, save the knowledge that it had been run in some variable and then check the status.
